In [1]:
import numpy as np

<h2> Методичка 3</h2>
<h3> Задача1</h3>

<p> Установить, какие произведения матриц AB и BA определены, и найти размерности полученных матриц:

а) A — матрица 4×2, B — матрица 4×2;

б) A — матрица 2×5, B — матрица 5×3;

в) A — матрица 8×3, B — матрица 3×8;

г) A — квадратная матрица 4×4, B — квадратная матрица 4×4.</p>

In [2]:
# a) перемножение невозможно количество столбцов матрицы А не равно количеству строк B
# проверка
A = np.ones((4,2))
B = np.ones((4,2))
try:
    C = A.dot(B)
except:
    print('ошибка несоответсвие форм матриц')

ошибка несоответсвие форм матриц


In [3]:
# б) перемножение возможно, форма матрицы 2х3
A = np.ones((2,5))
B = np.ones((5,3))

C = A.dot(B)
try:
    C = A.dot(B)
except :
    print('ошибка несоответсвие форм матриц')
print(C.shape, 'форма матрицы')

(2, 3) форма матрицы


In [4]:
# г) перемножение матриц возможно условие соблюдается? форма матрицы 4х4
A = np.ones((4,4))
B = np.ones((4,4))

C = A.dot(B)
try:
    C = A.dot(B)
except :
    print('ошибка несоответсвие форм матриц')
print(C.shape, 'форма матрицы')

(4, 4) форма матрицы


<h3> Задача2</h3>

<p> Найти сумму и произведение матриц $$A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} и B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$$.</p>

In [5]:
# Сумма матриц - матрица С = [ [5, -3], [3,5]]
# проверка
A = np.array([[1,-2], [3, 0]])
B = np.array([[4,-1], [0, 5]])

print(A+B, 'сумма матриц')

[[ 5 -3]
 [ 3  5]] сумма матриц


In [6]:
# Произведение матриц:
# C11 = 1*4 + (-2)*0 = 4
# C12 = 1 * (-1)+ (-2)*5 = -11
# C21 = 3*4  + 0*0 = 12
# C22 = 3 * (-1) + 0*5 = -3
#  C = [[4,-11], [12, -3]]

# проверка

print(A.dot(B), "Произведение матриц")

[[  4 -11]
 [ 12  -3]] Произведение матриц


<h3> Задача3</h3>

<p> Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$ </p>

In [7]:
# Вычислим 3А = [[3,21], [9, -18]]
# Вычислим -2B = [[0,-10], [-4, 2]]
# Вычислим -4C = [[8,-16], [4, 4]]
# Вычислим 3A - 2B = [[3,11],[5,-16]]
# Вычислим 3А-2B + 4C = [[11,-5], [9, -12]]

# Проверка
A = np.array([[1,7], [3,-6]])
B = np.array([[0,5], [2,-1]])
C = np.array([[2,-4], [1,1]])

print(3*A-2*B+4*C)

[[ 11  -5]
 [  9 -12]]


<h3> Задача4</h3>

<p>  Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$</p>

In [8]:
# Транспонируем матрицу А

A = np.array([[4,1], [5,-2], [2,3]])
# AT = [[4,5,2], [1, -2, 3]]
# проверка
AT = A.T
print(AT)

[[ 4  5  2]
 [ 1 -2  3]]


In [9]:
# Перемножаем матрицы, результат матрица 3х3

# AAT_11 = 4*4+1*1 =17
# AAT_12 = 4*5 + 1*(-2) = 20 -2 =18
# AAT_13 = 4 *2 + 1*3 = 8 + 2 = 11

# AAT_21 = 5*4+ -2*1 =20-2 =18
# AAT_22 = 5 * 5 + (-2) * (-2) = 25 + 4 = 29
# AAT_23 = 5*2+(-2)*3= 10 -6 = 4

# AAT_31 = 2*4+3*1=8+3=11
# AAT_32 = 2*5+3*(-2) = 10-6= 4
# AAT_33 = 2*2 + 3*3 = 4+9 = 13

# AAT = [[17,18,10], [18,29,4], [11,4,13]]
# Проверка
print(np.dot(A,A.T))

[[17 18 11]
 [18 29  4]
 [11  4 13]]


In [10]:
# Вычисляем AT * A, результа матрица размер 2х2

# ATA11 = (4  5  2) * (4 5 2) = 16+25+4 = 45
# ATA12 = (4  5  2) * (1 -2 3) = 4 -10 +6= 0
# ATA21 = (1 -2  3) * (4 5 2) = 4 -10 +6 = 0
# ATA22 = (1 -2  3) * (1 -2  3) = 1+4+9=14

#Проверка
print(np.dot(AT, A))

[[45  0]
 [ 0 14]]


<h3> Задача5</h3>

<p> Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy. </p>

In [11]:
# функция скалярного умношения векторов
def vec_dot(a,b):
    """ Вычисляет скалярное произведение векторов a и b размерностью n"""

    if len(a) == len(b) : # проверяем равенство размерностей векторов
        v_sum = 0
        for i in range(len(a)):
            v_sum += a[i]*b[i]
        return v_sum
    else: 
        raise Exception('Ошибка! Векторы должны быть одинаковой длины')
     

In [12]:
# функция перемножения произвольных матриц

def mat_dot(matA, matB):
    """ Выполняет перемножение двух матриц, результат перемножения - матрица"""
    #размерности матриц
    m = matA.shape[0]
    n = matB.shape[1]

    # создаем матрицу результата произведения
    matC = np.zeros((m,n))


    if matA.shape[1] == matB.shape[0]: # проверяем возможность перемножения количество сток матрицы B равно числу столбцов матрицы A
        for i in range(m):
            for j in range(n):
                matC[i,j] = vec_dot(matA[i,:], matB[:, j])
        return matC
    else:
        raise  Exception('Ошибка! Не выполняется условие перемножения матриц')


 

In [13]:
# проверка перемножение векторов
print(vec_dot([2,2,2], [3,3,3]))
print(np.dot([2,2,2], [3,3,3])) # результат должен совпадать

18
18


In [14]:
# вызываем исключение - размерность векторов
print(vec_dot([2,2,2], [3,3]))

Exception: Exception: Ошибка! Векторы должны быть одинаковой длины

In [20]:
# Проверка - перемножение матриц
A = np.array([[1,-2], [3, 0]])
B = np.array([[4,-1], [0, 5]])

print(mat_dot(A,B))
print(np.dot(A,B)) # результат должен совпадать

[[  4. -11.]
 [ 12.  -3.]]
[[  4 -11]
 [ 12  -3]]


In [15]:
# вызываем исключение размерность матриц
A = np.ones((4,2))
B = np.ones((4,2))

print(mat_dot(A,B))

Exception: Exception: Ошибка! Не выполняется условие перемножения матриц

<h2> Методичка 4</h2>
<h3> Задача1</h3>

<p> Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$</p>

In [16]:
# a) Вычисляется через определитель второго порядка произведение элементов главной диагонали минус произведение элементов побочной
# detA = sinx* sinx - (-cosx)*cosx = sin(x)^2 + cos(x)^2 = 1
# Проверка
A = np.array([[np.sin(45), -1*np.cos(45)], [np.cos(45), np.sin(45)]])

print('Определитель матрицы А', np.linalg.det(A))

Определитель матрицы А 1.0


In [17]:
# б) Для треугольной матрицы определитель произведение чисел на главной диагонали
# detB = 4*5*9 = 180
# Проверка
print(np.linalg.det([[4,2,3],[0,5,1],[0,0,9]]))

180.0


In [18]:
# в) Вычислим через миноры:
# detC = +(45-48) - (36-42) + (32-35) = -3 +6 -3 = 0
# Проверка
print(round(np.linalg.det([[1,2,3],[4,5,6], [7,8,9]]),2))

0.0


<h3> Задача2</h3>

<p> Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.</p>

In [19]:
# а) Исходя из смысла определителя (объем фигуры заданной векторами матрицы), то возведение матрицы в квадрат является
# перемножением объемов V*V = V^2.
# Проверим на численном примере
A = np.array([[2,2],[3,5]])
print(round(np.linalg.det(A),2)) # Определитель должен быть равен 4

4.0


In [20]:
# возведение в квадат матрицы A
A2 = np.dot(A,A)
print(A2)

[[10 14]
 [21 31]]


In [21]:
# определитель для A^2
print(round(np.linalg.det(A2),2)) # предположение подтвердилось

16.0


In [22]:
# б) По свойству определителя матрицы. Для исходной матрицы и транспонированной определители одинаковые
#Проверка
print(round(np.linalg.det(A.T),2))

4.0


In [23]:
# в) По свойству определителя при умножении строки (столбца) матрицы на число, определитель матрицы detA
#увеличивается на это число. Соответственно при умножении матрицы на число (k) определитель увеличится на соотношение:
# detkA = k^n*detA, где число строк(столбцов). Соответственно определитель det2A = 2^2*4 = 16
#Проверка

print("A = ", A)
print("det2A ",round(np.linalg.det(2*A),2)) # результат должен быть 2^2*4 = 16
print("det3A ",round(np.linalg.det(3*A),2)) # результат должен быть 3^2*4 = 36
print("det9A ",round(np.linalg.det(9*A),2)) # результат должен быть 9^2*4 = 324

A =  [[2 2]
 [3 5]]
det2A  16.0
det3A  36.0
det9A  324.0


<h3> Задача3</h3>

<p> Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.</p>

In [24]:
# Исходя из определения, вырожденная матрица - матрица определитель которой равен нулю.
# Найдем определитель для данной матрицы
A3 = np.array([[-2,7,-3],[4, -14, 6], [-3, 7, 13]])
print(np.linalg.det(A3))

0.0


<h3> Задача4<h3>
Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [25]:
# а)ранг матрицы равен 2, так как третья строка линейно зависима - сумма первой и второ строки
# проверка
A4 = np.array([[1,2,3], [1,1,1], [2,3,4]])
print("ранг матрицы", np.linalg.matrix_rank(A4))

ранг матрицы 2


In [26]:
# б) Ранг матрицы равен 3, строка 3 линейно зависимая - сумма первой и второй строики
# проверка

B4 = np.array([[0,0,2,1], [0,0,2,2,], [0,0,4,3], [2,3,5,6]])
print('Ранг матрицы', np.linalg.matrix_rank(B4))

Ранг матрицы 3
