In [29]:
import numpy as np

<h2> Методичка 6</h2>
<h3> Задача1</h3>
<p> Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$</p>

In [30]:
# Перепишем систему в присоединенную матрицу. Система является недоопределенной и имеет бесконечное число решений - общее решение
A = np.array([[1, 1, -1, -2, 0], [2, 1, -1, 1, -2], [1, 1, -3, 1, 4]])

In [31]:
# из 2 строки вычтем первую строку умношенную на 2
A[1, :] -= 2*A[0, :]
print(A)

[[ 1  1 -1 -2  0]
 [ 0 -1  1  5 -2]
 [ 1  1 -3  1  4]]


In [32]:
# из третьей строки вычтем первую
A[2, :] -= A[0, :]
print(A)

[[ 1  1 -1 -2  0]
 [ 0 -1  1  5 -2]
 [ 0  0 -2  3  4]]


In [33]:
# обозначим x4 как с и выразим x3 из третьего уравнения
# -2x3 +3c = 4 => -2x3 = 4-3c => x3 = 1.5c-2
# из второго уравнения выразим x2 через x3 x4
# -1x2 + 1.5c-2 + 5c = -2 => -1x2 +6.5c - 2 = -2 => -1x2 = -6.5c => x2 = 6.5c
# из первого уравнения найдем x1
# 1x1 + 6.5c - 1.5c+2 -2c = 0 => 1x1 +3c +2 =0 => x1=-3c-2
# Решение уравнения
# x4 = c; x3 = 1.5c-2; x2 = 6.5c; x1 = -3c-2
# Найдем частное решение пр с = 2
c =2 
x1 = -3*c-2
x2 = 6.5*c
x3 = 1.5*c -2
x4 = c
print(x1, '\t', x2, '\t', x3, '\t', x4,'\t')

-8 	 13.0 	 1.0 	 2 	


In [34]:
# Проверка: первое уравнение
print(x1+x2-x3-2*x4 ==0) #  вывод должен быть Тrue

True


In [35]:
print(2*x1+x2-x3+x4 == -2) #  второе уравнение

True


In [36]:
print(x1+x2-3*x3+x4 == 4) # третье уравнение

True


<h3> Задача2</h3>
<p> Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$</p>

In [37]:
# a) Проверим на совместность сравнив ранги матрицы коэфиициентов и дополненной матрицы
A1 = np.array([[3, -1, 1], [2, -5, -3], [1,1, -1]])
B1 = np.array([4, -17, 0]).reshape((-1,1))
AB = np.concatenate([A1,B1], axis=1)
AB

array([[  3,  -1,   1,   4],
       [  2,  -5,  -3, -17],
       [  1,   1,  -1,   0]])

In [38]:
print(np.linalg.matrix_rank(A1))
print(np.linalg.matrix_rank(AB))
#Ранги матриц совпадают и равны числу неизвестныз, система совместна и имеет одно решение

3
3


In [39]:
# б) Проверим на совместность сравнив ранги матрицы коэфиициентов и дополненной матрицы
A2 = np.array([[2, -4, 6], [1, -2, 3], [3,-6, 9]])
B2 = np.array([1, -2, 5]).reshape((-1,1))
AB2 = np.concatenate([A2,B2], axis=1)
AB2

array([[ 2, -4,  6,  1],
       [ 1, -2,  3, -2],
       [ 3, -6,  9,  5]])

In [40]:
print(np.linalg.matrix_rank(A2))
print(np.linalg.matrix_rank(AB2))
# ранг дополненной матрицы больше матрицы коэффициентов и ранги меньше числа неизвестных - система несовместна, решений не имеется

1
2


In [41]:
# в) Проверим на совместность сравнив ранги матрицы коэфиициентов и дополненной матрицы
A3 = np.array([[1, 2, 5], [3, 1, -8]])
B3 = np.array([4, -2]).reshape((-1,1))
AB3 = np.concatenate([A3,B3], axis=1)
AB3

array([[ 1,  2,  5,  4],
       [ 3,  1, -8, -2]])

In [42]:
print(np.linalg.matrix_rank(A3))
print(np.linalg.matrix_rank(AB3))

# Ранги матриц совпадают, но ранг меньше числа неизвестных - система недоопределена и имеет бесконечное число решений

2
2



 <h3> Задача3</h3>
 <p> 
 Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

 </p>

In [43]:
# найдем ранки матрицы коффициентов и расширенной матрицы
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0 ,0 ,0, 2]])
B = np.array([3, 2, 4, 1]).reshape((-1,1))
AB = np.concatenate([A, B], axis =1)
AB

array([[ 1,  3, -2,  4,  3],
       [ 0,  5,  0,  1,  2],
       [ 0,  0,  3,  0,  4],
       [ 0,  0,  0,  2,  1]])

In [44]:
# Определим ранги матриц
print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(AB))

4
4


In [45]:
# ранги матриц совпадают и равны числу неизвестных, следовательно система имеет единственное решение
print(np.linalg.solve(A, B).T) #  найдем вектор X

[[2.76666667 0.3        1.33333333 0.5       ]]


<h3> Задача4</h3>
 <p> 
 Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.
 </p>

In [46]:
# Решим систему Метод Гаусса
#  1  2  3  | a    1  2  3 | a       1  2  3 | a                1  2  3 | a
#  4  5  6  | b => 0 -3 -6 | b-4a => 0 -3 -6 | b-4a         =>  0 -3 -6 | b-4a
#  7  8  9  | c    0 -6 -12| c-7a    0  0  0 | c-7a + 2b+8a     0  0  0 | c+a-2b
#

In [47]:
# Третья строка матрицы линейно зависима. Матрица коэффициентов имеет ранг 2, для того чтобы ранг рассширенной матрицы был равень 2
# выражение a - 2b+c  должно быть равно нулю. 
# Таким образом система будет несовместна при соотношение a -2b+c  != 0 (не равных нулю)

In [48]:
# выражение a -2b+c  == 0 система будет имет решение
a = 3
b = 1
c = -1
print('a -2b+c  = ',a-2*b+c)
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([a,b,c]).reshape((-1,1))
AB = np.concatenate([A, B], axis = 1)
print(AB) 

a -2b+c  =  0
[[ 1  2  3  3]
 [ 4  5  6  1]
 [ 7  8  9 -1]]


In [49]:
print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(AB))

2
2


In [50]:
# выражение a -2b+c  != 0 система несовместна
a = 3
b = 1
c = 0
print('a -2b+c  = ',a-2*b+c)
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([a,b,c]).reshape((-1,1))
AB = np.concatenate([A, B], axis = 1)
print(AB) 

a -2b+c  =  1
[[1 2 3 3]
 [4 5 6 1]
 [7 8 9 0]]


In [51]:
print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(AB))

2
3


<h2> Методичка 7</h2>
<h3> Задача1</h3>
<p> Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$
</p>

In [52]:
# а) Определитель системы
# -4 +6 = 2
# определитель первого незвестного
#  1  -2 => -4 + 14 = 10 
#  7  -4 
# определитель второго незвестного
#  1  1  => 7 -3 = 4
#  3  7
# x1 = 10/2 = 5
# x2 = 4/2 = 2

#Проверка 5 -4 ==1
#          3*5 - 4*2 == 7

In [53]:
# АНалогично для второй системы исопльзуя numpy
A7 = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
B7 = np.array([[10, -2, 1]])

det0 = np.linalg.det(A7) # определитель матрицы коэффциентов
A7_1 = np.copy(A7)
A7_1[:,0] = B7 # заменяем первый столбец на вектор B
det1 = np.linalg.det(A7_1) # определитель для первого незвестного
print(A7_1, '\n')

A7_2 = np.copy(A7)
A7_2[:,1] = B7 # заменяем второй столбец на вектор B
det2 = np.linalg.det(A7_2) # определитель для второго незвестного
print(A7_2, '\n')

A7_3 = np.copy(A7)
A7_3[:,2] = B7 # заменяем третий столбец на вектор B
det3 = np.linalg.det(A7_3) # определитель для третьего незвестного
print(A7_3, '\n')

[[10 -1  5]
 [-2  1 -3]
 [ 1  4  1]] 

[[ 2 10  5]
 [ 1 -2 -3]
 [ 2  1  1]] 

[[ 2 -1 10]
 [ 1  1 -2]
 [ 2  4  1]] 



In [54]:
# Надем вектор X
X = np.array([0,0,0])
X[0] = det1/det0
X[1] = det2/det0
X[2] = det3/det0
X = X.reshape((-1,1))
print(X) # Корни уравнения

[[ 2]
 [-1]
 [ 1]]


In [55]:
# Проверка A*X = b
print(A7)
print()
print(np.dot(A7,X))

[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]

[[10]
 [-2]
 [ 1]]
